kp: 1.0
kd: 2.0
h : 0.5
nom_dist: 0.5
kpATK:  3.0
kdATK: -1.0
hATK :  0.5

L: 0.31  # vehicle width

controller_rate:  50.
sensor_rate:      70. 
high_level_rate:  5

# only use these for the big cars
# ll_kp: 0.75 
# ll_ki: 5.25
# ll_kd: 0.0005
pwm_sat: 0.85 # pwm saturation limit. set to 0.95 during performance mode

curv_kp: 1.1
lookahead: 20
magnet_ofs: 0.0

# kalman filer gains
Q11: 0.0   # distance noise
Q22: 200.0 # velocity noise
Q33: 0.0   # theta noise
Q44: 5000.0 # theta dot noise
R11: 0.0002
R22: 0.01
R33: 1

Plim_r: 20
Plim_th: 2000
min_r: 0.1
max_r: 8
max_th: 60 



